// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BoxContainer: typeof import('./src/components/BoxContainer.vue')['default']
    ButtonList: typeof import('./src/components/ButtonList.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Chart: typeof import('./src/components/Chart/src/Chart.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DigitalFlop: typeof import('./src/components/DigitalFlop.vue')['default']
    EchartMap: typeof import('./src/components/Chart/src/EchartMap.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ExportExcelModal: typeof import('./src/components/Excel/src/ExportExcelModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImportExcel: typeof import('./src/components/Excel/src/ImportExcel.vue')['default']
    LoopScroll: typeof import('./src/components/LoopScroll.vue')['default']
    PageFooter: typeof import('./src/components/Page/src/PageFooter.vue')['default']
    PageWrapper: typeof import('./src/components/Page/src/PageWrapper.vue')['default']
    Pagination: typeof import('./src/components/Pagination/Pagination.vue')['default']
    RadioGroup: typeof import('./src/components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowNotice: typeof import('./src/components/RowNotice.vue')['default']
    SearchButton: typeof import('./src/components/SearchButton.vue')['default']
    SearchContainer: typeof import('./src/components/SearchContainer.vue')['default']
    Table: typeof import('./src/components/Table/Table.vue')['default']
    TextEllipsis: typeof import('./src/components/TextEllipsis.vue')['default']
  }
}
