// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BoxContainer: typeof import('./src/components/BoxContainer.vue')['default']
    ButtonList: typeof import('./src/components/ButtonList.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Chart: typeof import('./src/components/Chart/src/Chart.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DigitalFlop: typeof import('./src/components/DigitalFlop.vue')['default']
    EchartMap: typeof import('./src/components/Chart/src/EchartMap.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ExportExcelModal: typeof import('./src/components/Excel/src/ExportExcelModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IAntDesignQuestionCircleOutlined: typeof import('~icons/ant-design/question-circle-outlined')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    ImportExcel: typeof import('./src/components/Excel/src/ImportExcel.vue')['default']
    LoopScroll: typeof import('./src/components/LoopScroll.vue')['default']
    PageFooter: typeof import('./src/components/Page/src/PageFooter.vue')['default']
    PageWrapper: typeof import('./src/components/Page/src/PageWrapper.vue')['default']
    Pagination: typeof import('./src/components/Pagination/Pagination.vue')['default']
    RadioGroup: typeof import('./src/components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowNotice: typeof import('./src/components/RowNotice.vue')['default']
    SearchButton: typeof import('./src/components/SearchButton.vue')['default']
    SearchContainer: typeof import('./src/components/SearchContainer.vue')['default']
    Table: typeof import('./src/components/Table/Table.vue')['default']
    TextEllipsis: typeof import('./src/components/TextEllipsis.vue')['default']
  }
}
