// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppDarkModeToggle: typeof import('./src/components/Applicatioin/src/AppDarkModeToggle.vue')['default']
    AppLocalePicker: typeof import('./src/components/Applicatioin/src/AppLocalePicker.vue')['default']
    AppLogo: typeof import('./src/components/Applicatioin/src/AppLogo.vue')['default']
    AppProvider: typeof import('./src/components/Applicatioin/src/AppProvider.vue')['default']
    AppSearch: typeof import('./src/components/Applicatioin/src/search/AppSearch.vue')['default']
    AppSearchFooter: typeof import('./src/components/Applicatioin/src/search/AppSearchFooter.vue')['default']
    AppSearchKeyItem: typeof import('./src/components/Applicatioin/src/search/AppSearchKeyItem.vue')['default']
    AppSearchModal: typeof import('./src/components/Applicatioin/src/search/AppSearchModal.vue')['default']
    BoxContainer: typeof import('./src/components/BoxContainer.vue')['default']
    ButtonList: typeof import('./src/components/ButtonList.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Chart: typeof import('./src/components/Chart/src/Chart.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DigitalFlop: typeof import('./src/components/DigitalFlop.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown/src/Dropdown.vue')['default']
    EchartMap: typeof import('./src/components/Chart/src/EchartMap.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ExportExcelModal: typeof import('./src/components/Excel/src/ExportExcelModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'IIon:language': typeof import('~icons/ion/language')['default']
    ImportExcel: typeof import('./src/components/Excel/src/ImportExcel.vue')['default']
    LoopScroll: typeof import('./src/components/LoopScroll.vue')['default']
    PageFooter: typeof import('./src/components/Page/src/PageFooter.vue')['default']
    PageWrapper: typeof import('./src/components/Page/src/PageWrapper.vue')['default']
    Pagination: typeof import('./src/components/Pagination/Pagination.vue')['default']
    RadioGroup: typeof import('./src/components/RadioGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowNotice: typeof import('./src/components/RowNotice.vue')['default']
    SearchButton: typeof import('./src/components/SearchButton.vue')['default']
    SearchContainer: typeof import('./src/components/SearchContainer.vue')['default']
    Table: typeof import('./src/components/Table/Table.vue')['default']
    TextEllipsis: typeof import('./src/components/TextEllipsis.vue')['default']
  }
}
